# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 22:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20170322_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_in_dollars',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='catalog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 22, 22, 48, 30, 728387, tzinfo=utc)),
        ),
    ]
