# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-23 22:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20170323_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 23, 22, 15, 26, 899850, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 23, 22, 15, 26, 904724, tzinfo=utc)),
        ),
    ]
